### ISSUE TITLE
error: ['EAPI:Invalid key'] doing fetchBalance for Kraken 

### ISSUE THREAD

**Issue by dpyro** [kroitor/ccxt#52] opened 2017-07-25 18:54 UTC
Using Node.JS 8.1.4 I receive this error after instantiation with the api key and private key from Kraken.

```typescript
const market = new ccxt[key]({
  apiKey: data.apiKey,
  secret: data.secret
})

console.log(await market.fetchBalance())
```

Public functions seem to work fine.

**Comment by kroitor** [comment] 2017-07-25 19:11
Thank you for posting this! Is this a new fresh API keypair, or did you use it previously? This may be a nonce issue. I will check and report soon.

**Comment by kroitor** [comment] 2017-07-25 20:04
Yeah, it looks like a Node-only issue, Python and PHP working normally. I am debugging this right, should upload the fix soon. Thanks!

**Comment by dpyro** [comment] 2017-07-25 20:38
Thanks for the quick reponse! For clarification, this was a freshly generated keypair that I've only used with this library.

**Comment by kroitor** [comment] 2017-07-25 21:04
> For clarification, this was a freshly generated keypair that I've only used with this library.
Yep, we found the problem (it is due to switching from crypto → crypto-js under Node). We will fix it as soon as possible and it will be working in the next release (this may take a couple of hours for testing), thanks for your patience.

**Comment by kroitor** [comment] 2017-07-25 23:43
Ok, we now have a fix for this issue, it should be available in version 1.1.81 already. The Kraken exchange should also work normally. We made a special case for the beast, that is, until we find a more elegant solution to this problem. 

Code for testing:
```JavaScript
const ccxt = require ('ccxt')
const kraken = new ccxt.kraken ({
    apiKey: 'CGAra4mIwKxgV3uYB4XZI4nVVmjXyIpER+5bFUuXGlIQ4MJFKLQfTJWK',
    secret: 'wrkstzsrwdj9pJlUGjj+wOTQgYAaO8MankKJPhASNGEY7hbFAtumQ45C7K/2SwCSgL8WcusUuTgarP5mmqo1uQ=='
})
(async () => {
    await kraken.loadProducts ()
    console.log (await kraken.fetchBalance ())
}) ()
```

This snippet should output the following:

```bash
{ info: {} } # no error, just an empty balance
```

Please, test it in your console and report if you have any errors. Thank you!

**Comment by kroitor** [comment] 2017-07-26 01:45
Can you please report whether this issue is gone on your side? Thank you!

**Comment by kroitor** [comment] 2017-07-26 03:43
I'm closing this down because Kraken is now confirmed to be working properly. Please reopen if you still have issues with it! Thank you!

**Closed by kroitor** 2017-07-26 03:43 UTC

**Comment by dpyro** [comment] 2017-07-26 06:16
I can confirm the updated code works. Thanks!

**Comment by kroitor** [comment] 2017-07-26 06:17
Thank you too, your help is appreciated!

**Comment by kroitor** [comment] 2017-07-30 13:18
We have finally integrated an adequate solution for Kraken, and removed that ugly workaround! ) Module crypto is now removed from dependencies completely!

**Comment by kvz** [comment] 2017-11-13 21:20
Hi, thanks for this awesome project! Question, I'm seeing `kraken {"error":["EAPI:Invalid nonce"]}` when running `fetchBalance` even though I'm on the latest 1.10.82. Any clue?

**Comment by kroitor** [comment] 2017-11-13 21:22
@kvz, hi!

Did you use the keys with any other software previously or is it a fresh new keypair?

**Comment by kroitor** [comment] 2017-11-13 21:24
@kvz try a new keypair and if it works, it means that the old keys have been used with a software that computes the nonce value differently. If the new keypair works, but you still want to use that old keypair, you will need to override the nonce for it. More about it here: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting.

**Comment by kvz** [comment] 2017-11-14 09:36
Hi @kroitor, thanks for the assistance 👍  

I gerenated a new API key with the following settings:

![screen shot 2017-11-14 at 10 22 26](https://user-images.githubusercontent.com/26752/32772321-c568c656-c925-11e7-8ec5-89de30cb38a8.png)

and the issue seems resolved, thanks! 💯  🥇

**Comment by kvz** [comment] 2017-11-17 15:57
I still get an occasional nonce error. I increased the Nonce window a bit and that helped somewhat (i think) I fully blame Kraken for the flakyness tho.

**Comment by kroitor** [comment] 2017-11-17 16:03
@kvz 

Lags are well-known, those are on Kraken side. Most users report the same (not only ccxt users, but most of Kraken users).

https://status.kraken.com/

<img width="887" alt="screen shot 2017-11-17 at 19 02 21" src="https://user-images.githubusercontent.com/1294454/32956448-df89009a-cbc9-11e7-86ec-5e64ac8dcc29.png">

**Comment by bluppfisk** [comment] 2018-09-26 18:37
I wonder if you've ever found a workaround that does use crypto-js instead of crypto? I need to implement he same but without access to crypto. :(

Below works, as in the signature gets accepted, but I get "Invalid Key". Wonder if it's the stringification?

```
const getMessageSignature = (path, request, secret, nonce) => {
    // API-Sign = Message signature using HMAC-SHA512 of (URI path + SHA256(nonce + POST data)) and base64 decoded secret API key
    const message = JSON.stringify(request);

    const secret_buffer = btoa(secret);
    const hash = CryptoJS.algo.SHA256.create();
    const hmac = CryptoJS.algo.HMAC.create(CryptoJS.algo.SHA512, secret_buffer);
    const hash_digest = hash.update(nonce + message).finalize().toString(CryptoJS.enc.Hex);
    const hmac_digest = hmac.update(path + hash_digest).finalize().toString(CryptoJS.enc.Base64);

    // CANNOT USE BELOW (Buffer and crypto not supported)
    // const secret_buffer = new Buffer(secret, 'base64');
    // const hash = new crypto.createHash('sha256');
    // const hmac = new crypto.createHmac('sha512', secret_buffer);
    // const hash_digest = hash.update(nonce + message).digest('binary');
    // const hmac_digest = hmac.update(path + hash_digest, 'binary').digest('base64');

    return hmac_digest;
};
```

**Comment by Morriz** [comment] 2018-12-26 14:39
Any update on this? Is it possible to make this lib work with pure js only? Some of us build client apps.

**Comment by kroitor** [comment] 2018-12-26 14:43
@Morriz the current version of CCXT does not use `crypto` (uses `CryptoJS` instead) and should allow to work with Kraken with pure js. Do you have an issue with it?

**Comment by Morriz** [comment] 2018-12-26 14:47
Oh, sry about my ignorance! I did not know. Let me try :)

**Comment by kroitor** [comment] 2018-12-26 14:52
@Morriz no worries, however, i'd recommend to start from here:

- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
- https://github.com/ccxt/ccxt/wiki/Manual

Let us know if you have any questions after that )

**Comment by Morriz** [comment] 2018-12-30 12:13
Nope. Kindly stole your cryptojs setup to make my app work without a proxy, before adding "use ccxt as api client" to my issue list. Which will have quite some impact, but might make it easier to open up the app to multiple exchanges. Do you think there are many big exchanges that could easily be interfaced with your library, without doing a lot of plumbing per exchange? What coverage does the library have when it comes to shared functionality? Like 90% or less? And where can I take this conversation? I am considering open sourcing the app if there would be interest in having an intuitive general trading app that could connect with multiple exchanges.

**Comment by Morriz** [comment] 2018-12-30 12:15
The app is now on the play store, and was born out of my frustration with Kraken not having an app, and me only being able to trade there, because of the EUR deposit issues back in early 2017.

https://play.google.com/store/apps/details?id=nl.idiotz.krakenfx
