### ISSUE TITLE
Unified fetchOrder, is it possible?

### ISSUE THREAD

**Issue by Nilotaviano** [kroitor/ccxt#96] opened 2017-08-10 14:16 UTC
fetchOrder was implemented for chbtc on #74. I was trying to implement it for liqui, poloniex and bittrex, but there's nothing like "getOrder" on poloniex, so I don't think it's possible without ugly "workarounds", like emulating it using "returnOpenOrders", "returnOrderTrades" and/or "returnTradeHistory". This might be the same for some other exchanges, I'm not sure.

I'm just wondering if it would be worth it to make fetchOrder part of the unified API, what do you think?

**Comment by kroitor** [comment] 2017-08-10 14:27
Yes, we have plans to unify the fetchOrder. Your help will be much appreciated as well (with those exchanges that you can handle without a big pain). We will update you on this, and, in the meantime, if you don't mind, I'm closing this issue as a duplicate of https://github.com/kroitor/ccxt/issues/71 ?

**Comment by Nilotaviano** [comment] 2017-08-10 14:30
Sure! I missed that one, sorry.

**Closed** 2017-08-10 14:33 UTC
