### ISSUE TITLE
Kraken: KeyError: 'txid'

### ISSUE THREAD

**Issue by janktrader** [kroitor/ccxt#143] opened 2017-08-22 18:14 UTC
When placing a trade (buy or sell limit order is all I tried) on Kraken the order goes through but the code returns a KeyError: 'txid' on length = len(response['txid']) within create_order

**Comment by kroitor** [comment] 2017-08-22 19:24
Hi! In order to help, we need to see your code and your full stacktrace in verbose mode: https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
Thx!

**Comment by kroitor** [comment] 2017-08-22 23:26
@janktrader I've added a fix for this, please update to 1.4.87+ and see if the problem is gone for you. Thanks!

**Comment by kroitor** [comment] 2017-08-23 14:25
@janktrader hi! Does that fix solve your issue?

**Comment by janktrader** [comment] 2017-08-23 14:45
@kroitor Sorry, was just able to test it and it works now. Thanks for the help. Now to implement fetchMyOpenOrders for Kraken. I would do it but I do not know how to change any of the non python files.

**Comment by kroitor** [comment] 2017-08-23 14:52
@janktrader if you can do it in Python in the same way it is implemented in a few places already, literally copying the codeflow and styling (which may seem 'very basic' at first, but that is intentional, for portability), and if you can follow [the CONTRIBUTING document](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md) and in particular [these guidelines](https://github.com/kroitor/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes) and then submit a PR, it would be awesome! If you do that we will port it and merge it, of course! Please let us know if you will, so that we don't do the same work twice ) Thx!

**Closed** 2017-08-23 14:52 UTC

**Comment by janktrader** [comment] 2017-08-23 14:58
@kroitor OK man I will try. I actually tried just copying the function from a different exchange and putting into Krake's class but I got an error with self.privatePostReturnOpenOrders because I couldn't figure out where to declare that.

**Comment by kroitor** [comment] 2017-08-23 15:02
@janktrader that is self-declared automatically upon instantiation in the `define_rest_api()` base method from the endpoint schema (`self.api`) as written here: https://github.com/kroitor/ccxt/wiki/Manual#api-method-naming-conventions
If you really want to do it it properly, I'd recommend to read the entire Manual carefully before you start. ;)

If you have any questions, feel free to ask, we will help as quickly as we can. Thank you!
