### ISSUE TITLE
EOrder:Trading agreement required

### ISSUE THREAD

**Issue by chrniem** [kroitor/ccxt#58] opened 2017-07-26 07:53 UTC
Hi, 
I'm getting the Error: EOrder:Trading agreement required when I try to add a Order on kraken.
In the API Doc it says: 
**_If you receive the error "EOrder:Trading agreement required", refer to your API key management page for further details._**
and then API key management says: 
**_To indicate your agreement to the above statement and enable the orders in the API, set trading_agreement = agree in the AddOrder API._**

Is it possible to accept the agreement with your code or do I have to find another way?

Thanks

**Comment by kroitor** [comment] 2017-07-26 07:57
Yes, sure, don't know which language you're using, here's a sample in JS:
```
yourOtherParams = { 'trading_agreement': 'agree' }
kraken.createLimitSellOrder ('BTC/USD', 1, 3000, yourOtherParams)
```
It should be basically the same in Python and PHP

**Comment by kroitor** [comment] 2017-07-26 07:58
Don't execute that code, or it might place an unwanted order, it's for reference. Please report if it doesn't help you.

**Comment by kroitor** [comment] 2017-07-26 08:02
A longer syntax to do the same:
```JavaScript
yourOtherParams = { 'trading_agreement': 'agree' }
kraken.createOrder ('BTC/USD', 'limit', 'sell', 1, 3000, yourOtherParams)
```

**Comment by chrniem** [comment] 2017-07-26 08:05
I'm using python and tried this:

yourOtherParams  = {'trading_agreement':'agree'}
erg = kraken.create_market_buy_order('XRP/BTC', 0.001, yourOtherParams )

and still got: 
{'error': ['EOrder:Trading agreement required']}

**Comment by kroitor** [comment] 2017-07-26 08:14
Nah, ignore my previous comments, I was totally incorrect. It may be an issue with your account or your API keys, can you try to create a new keypair to see if this problem persists? Also, you might need to click some checkboxes in your Kraken account to allow order placement with their API. If this problem persists with a new fresh keypair, and you don't see any means to solve it within their website, we would recommend contacting their support then, to see if there's an issue with your account. They could also tell you the exact reason for that.

**Comment by kroitor** [comment] 2017-07-26 08:19
I would also be very thankful, if you report what they told you on the problem, so that other users would be less confused if they catch the same error.

**Comment by chrniem** [comment] 2017-07-26 08:26
Thanks for your immediate support!

I found something on clikraken, they seem to have that agreement option implemented.
To me it seems that it is for first time api users on kraken.

 https://github.com/zertrin/clikraken/blob/master/src/clikraken/api/private/place_order.py

**Comment by kroitor** [comment] 2017-07-26 08:28
From clikraken:

<img width="505" alt="screen shot 2017-07-26 at 11 27 31" src="https://user-images.githubusercontent.com/1294454/28611757-7ef93b88-71f5-11e7-9216-0438a88d2e00.png">

Well... they do it exactly the same way as I told you, but if it didn't work... then...

<img width="905" alt="screen shot 2017-07-26 at 11 26 22" src="https://user-images.githubusercontent.com/1294454/28611688-4aed3ea2-71f5-11e7-96a4-e9b92062eefb.png">

**Comment by kroitor** [comment] 2017-07-26 08:31
Also, turn verbosity on, to see if that parameter gets passed in request body. Set `kraken.verbose = True` on your instance prior to placing the order to see what it's sending to Kraken.

**Comment by kroitor** [comment] 2017-07-26 08:34
That 'trading_agreement' parameter is undocumented, I'm sorry we can't do much about it, except for contacting their support for them to resolve this.

**Comment by chrniem** [comment] 2017-07-26 08:38
If I'm getting it right, it seems to me the request didn't add the parameter:
https://api.kraken.com/0/private/AddOrder POST {'Content-type': 'application/x-www-form-urlencoded', 'API-Key': 'xxx', 'User-Agent': 'ccxt/1.1.83 (+https://github.com/kroitor/ccxt) Python/3.5.2', 'API-Sign': b'xxx'} volume=0.001&pair=XXRPXXBT&nonce=1501058177&ordertype=market&type=buy

**Comment by kroitor** [comment] 2017-07-26 08:39
Ok, we will debug it now then, and release a new patched version for this. Stand by, please, it may take an hour for testing.

**Comment by kroitor** [comment] 2017-07-26 08:57
We found a bug with this, now testing and uploading the fix. It should be available in new release 1.1.85 in 30-40 minutes. Thanks for your patience!

**Comment by kroitor** [comment] 2017-07-26 09:38
Ok, this is fixed now in version 1.1.85. Please update the library package and try your previous code to see if the problem is solved. We would be thankful if you report back. Thank you!

**Comment by chrniem** [comment] 2017-07-26 10:23
It works great.
Thanks for your great support and the immediate response.
I appreciate the whole project a lot!

Thanks and best greetings

Chris

**Comment by kroitor** [comment] 2017-07-26 10:23
Thanks you for your involvement!

**Closed by kroitor** 2017-07-26 10:23 UTC

**Comment by kroitor** [comment] 2017-07-27 20:09
Though this issue is already fixed in ccxt, here's an update, this is what Kraken replied:
```

Emily (Kraken Support) Jul 27, 13:05 PDT
Hi,This is an issue with your API permissions. Please try to navigate to the Trade-tab using the web interface, and then to the New Order page and then select Advanced there. You should be prompted with a trading agreement you have to accept. Once you have accepted this agreement you should not be prompted with this message.I hope this has answered your question, if not please feel free to respond and this ticket will be reopened.
Emily W.
Kraken Client Engagement
```

<img width="913" alt="screen shot 2017-07-27 at 23 06 58" src="https://user-images.githubusercontent.com/1294454/28690031-6a161d90-7320-11e7-8e4f-a9c4c623d6f7.png">
