### ISSUE TITLE
New exchange request: Nova Exchange

### ISSUE THREAD

**Issue by pelletiermaxime** [kroitor/ccxt#208] opened 2017-09-16 17:39 UTC
https://novaexchange.com/
API doc at https://novaexchange.com/remote/faq/.
It's a small exchange used by many new/small alt coins because it is relatively easy to get added.

Thanks for considering it !

**Comment by kroitor** [comment] 2017-09-16 17:56
Hi! We'll add it in several hours, thanks for your proposal!

**Comment by kroitor** [comment] 2017-09-17 11:44
We have added an experimental integration of the Nova Exchange under id *nova*.
It will be available in version 1.7.20+.

The problem is: we were only able to test their public API, because they don't accept new user registrations now. When I submit a sign up form on their site it says that their registration functionality is under maintenance and I should return later, but they don't say how long it will take...

![screen shot 2017-09-17 at 13 50 19](https://user-images.githubusercontent.com/1294454/30520124-a0cad044-9baf-11e7-8fae-ec7a46ac5aba.png)

Now our options are:
1. We will be happy if you would be so kind to send us a zero-balance keypair for testing (better do it by email if you agree), like other users did in their previous requests. We don't need your money nor your personal info, it's for testing purposes only.
2. You can try and test the private unified methods (fetchBalance, createOrder, cancelOrder) and report back here, it would also be very helpful.

I'm closing this issue for now, if you don't mind. Feel free to reopen it, if needed. 
Let us know if you have questions or if you have any difficulty with it.

Thx!

**Closed** 2017-09-17 11:44 UTC
Labels: enhancement

**Comment by pelletiermaxime** [comment] 2017-09-17 15:08
Wow, that was fast. Thanks!
Sadly I just tried the fetchBalance and I have the error:
`Uncaught (in promise) TypeError: _this561.privateGetBalances is not a function at ccxt.js:15253.`
I could send you a key/secret to my account. To be sure, your email is igor.kroitor@gmail.com ?

**Comment by kroitor** [comment] 2017-09-17 16:06
@pelletiermaxime Yep, that was a minor bug (a typo), I uploaded a fix for it, should be available in version 1.7.29+ in several minutes. Can you please try it again? Thx!
